version: '3'

services:

  diag-postgres:
    image: "postgres:13-alpine"
    restart: always
    container_name: diag-postgres
    volumes:
      - diag_postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=diag
      - POSTGRES_USER=diag
      - POSTGRES_PASSWORD=diag

    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-h", "localhost", "-U", "diag"]
      interval: 10s
      timeout: 5s
      retries: 3

  diag-app:
    build: ./backend
    container_name: diag-app
    restart: always
    environment:
      - DB_SERVER=diag-postgres
      - POSTGRES_DB=diag
      - POSTGRES_USER=diag
      - POSTGRES_PASSWORD=diag
      - SPRING_PORT=${SPRING_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

    ports:
      - '${SPRING_PORT}:${SPRING_PORT}'
    links:
      - diag-postgres
    depends_on:
      - diag-postgres

volumes:
  diag_postgres_data:
