spring:
  application:
    name: Wadiag-app
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:5432/diag
    username: diag
    password: diag
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: diag-kafka:9093

  liquibase:
    enabled: true
    change-log: classpath:/db/changelogs/db.changelog-master.xml

  profiles:
    active: dev
  config:
    import: optional:file:./application-${spring.profiles.active}.yml

logging:
  level:
    root: INFO
    web: INFO
    org:
      springframework: INFO
      hibernate: INFO
      com:
        dime:
          wadiag: INFO

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    urlsPrimaryName: public-apis
    defaultModelsExpandDepth: -1

  show-actuator: true

# Configure Actuator endpoints
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator

wordsapi:
  host:
    url: https://wordsapiv1.p.rapidapi.com
    key: # get api key here: https://rapidapi.com/dpventures/api/wordsapi/
