spring:
  application:
    name: Wadiag log
  kafka:
    log:
      bootstrap-servers: localhost:9092
      topic:
        create-log: create-log
      consumer:
        auto-offset-reset: earliest
        group-id:
          notification: notification
          service: service

  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:5432/diag-log
    username: diag-log
    password: diag-log
    driver-class-name: org.postgresql.Driver

  profiles:
    active: dev

logging:
  level:
    root: INFO
    web: INFO
    org:
      springframework: INFO
      hibernate: INFO
      dime:
        wadiag: INFO

server:
  port: 8085

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    urlsPrimaryName: public-apis
    defaultModelsExpandDepth: -1

  show-actuator: true

# Configure Actuator endpoints
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  security:
    enabled: false
