spring:
  application:
    name: Wadiag-log
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:5432/diaglog
    username: diaglog
    password: diaglog
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: diag-kafka:9093

  profiles:
    active: dev

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    urlsPrimaryName: public-apis
    defaultModelsExpandDepth: -1

  show-actuator: true

# Configure Actuator endpoints
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  metrics:
    tags:
      application: ${spring.application.name}
