global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "diag-app"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s
    static_configs:
      - targets:
          - docker.for.mac.localhost:8081
        labels:
          application: diag-app
  - job_name: "diag-log"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s
    static_configs:
      - targets:
          - docker.for.mac.localhost:8085
        labels:
          application: diag-log
  - job_name: "prometheus"
    static_configs:
      - targets:
          - prometheus:9090
