apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    version: 1
    editable: false
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    version: 1
    editable: false
    jsonData:
      maxLines: 1000
      minInterval: 1s
