apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    version: 1
    editable: false
  - name: loki
    access: proxy
    type: loki
    url: http://loki:3100
    isDefault: true
    database: ""
    user: ""
    password: ""
    basicAuth: false
    id: 1
    orgId: 1
    readOnly: false
    jsonData:
      keepCookies: []
    typeLogoUrl: public/app/plugins/datasource/loki/img/loki_icon.svg
