spring:
  application:
    name: Wadiag Application
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc:
            lob:
              on_contextual_creation: true
  datasource:
    url: jdbc:postgresql://diag-postgres:5432/diag
    username: diag
    password: diag
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelogs/db.changelog-master.xml
  profiles:
    active: dev
  config:
    import: optional:file:./application-${spring.profiles.active}.yml

logging:
  level:
    root: info
    web: debug
    org.springframework.web: info
    org.hibernate: info

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true

# Configure Actuator endpoints
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  security:
    enabled: false
wordsapi:
  host:
    url: https://wordsapiv1.p.rapidapi.com
