spring:
  application:
    name: Wadiag Application
  jpa:
    open-in-view: true

  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:5432/diag
    username: diag
    password: diag
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelogs/db.changelog-master.xml

  profiles:
    active: dev
    config:
      import: optional:file:./application-${spring.profiles.active}.yml

logging:
  level:
    root: INFO
    web: INFO
    org.springframework: INFO
    org.hibernate: INFO
    com.dime.wadiag: INFO

server:
  port: ${SPRING_PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true

# Configure Actuator endpoints
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  security:
    enabled: false

wordsapi:
  host:
    url: https://wordsapiv1.p.rapidapi.com
