name: CI/CD
# Name of the workflow, you can change this to a more descriptive name if needed.

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '22 19 * * 6'
  # Define the trigger conditions for the workflow:
  # - On push to the master branch
  # - On pull requests targeting the master branch
  # - Scheduled to run every Saturday at 7:22 PM

jobs:
  build_and_analyze:
    runs-on: ubuntu-latest
    # Define the job to run on the latest version of Ubuntu.

    env:
      JAVA_HOME: /opt/java/jdk17
      MAVEN_HOME: /opt/maven
      # Define environment variables for Java and Maven paths.

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      # Step to check out the project's source code.

    - name: Set up Java and Maven
      uses: actions/setup-java@v2
      with:
        distribution: "temurin"
        java-version: 17
        maven-version: 3.8
        cache: 'c:/temp/maven'
      # Step to set up Java and Maven with caching for improved performance.

    - name: Build and Test
      run: |
        cd backend
        mvn -B package --file pom.xml
        mvn --batch-mode test
      env:
        MAVEN_HOME: ${{ env.MAVEN_HOME }}
      # Step to build and test the Java project using Maven.

    - name: Test Reporter
      uses: dorny/test-reporter@v1.7.0
      with:
        name: test-results
        path: backend/target/surefire-reports/*.xml
        path-replace-backslashes: false
        reporter: java-junit
        list-suites: all
        list-tests: all
        max-annotations: 10
        fail-on-error: true
        fail-on-empty: true
        only-summary: false
        token: ${{ secrets.GITHUB_TOKEN }}
      # Step to report test results to GitHub.

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'java-kotlin'
      # Step to initialize CodeQL for Java and Kotlin.

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
      # Step to autobuild the CodeQL database.

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:java-kotlin"
      # Step to perform CodeQL analysis on the Java and Kotlin code.
