name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '22 19 * * 6'

jobs:
  build_and_analyze:
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java-kotlin', 'swift' ]

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: "temurin"
        java-version: 17
        node-version: 16  # Add this line to specify Node.js version 16

    - name: Build with Maven
      run: cd backend && mvn -B package --file pom.xml

    - name: Test
      run: cd backend && mvn --batch-mode test
      
    - name: Test Reporter
      uses: dorny/test-reporter@v1.7.0
      with:
        name: test-results
        path: backend/target/surefire-reports/*.xml
        path-replace-backslashes: false
        reporter: java-junit
        list-suites: all
        list-tests: all
        max-annotations: 10
        fail-on-error: true
        fail-on-empty: true
        only-summary: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
