name: Test Reporter

on: [push]  # Specify the events that should trigger this workflow, e.g., "push," "pull_request."

jobs:
  test-report:
    runs-on: ubuntu-latest  # Specify the runner's operating system.

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Use the checkout action to fetch your code.

    - name: Build
      run: mvn --batch-mode package
      
    - name: Test Reporter
      uses: dorny/test-reporter@v1.7.0
      with:
        name: test-results
        path: target/surefire-reports/*.xml
        path-replace-backslashes: false
        reporter: java-junit
        list-suites: all
        list-tests: all
        max-annotations: 10
        fail-on-error: true
        fail-on-empty: true
        only-summary: false
        token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub Token secret for authentication.
