name: 'Test Report'
on:
  workflow_run:
    workflows: ['Java CI with Maven and PostgreSQL']  # runs after CI workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results                # artifact name
        name: test-results                    # Name of the check run which will be created
        path: target/surefire-reports/*.xml   # Path to test results (inside artifact .zip)
        reporter: java-junit                  # Format of test results
