name: Java CI with Maven and Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 7 * * *'
    # Schedule: Run every day at 7:00 AM

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: diag
          POSTGRES_USER: diag
          POSTGRES_DB: diag
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java-kotlin' ]

    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Configuration File
        run: |
          mkdir -p /home/runner/work/wadiag/wadiag/backend/src/main/resources/private/
          echo "wordsapi.host.key=${{ secrets.WORDSAPI_API_KEY }}" > /home/runner/work/wadiag/wadiag/backend/src/main/resources/private/conf.properties
        shell: bash
  
      - name: List Files in Directory
        run: cd && tree
        shell: bash

      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Build with Maven
        run: cd backend && mvn -B package --file pom.xml
        
      - name: Test
        run: cd backend && mvn --batch-mode test
      
      - name: Test Reporter
        uses: dorny/test-reporter@v1.7.0
        with:
          name: test-results
          path: backend/target/surefire-reports/*.xml
          path-replace-backslashes: false
          reporter: java-junit
          list-suites: all
          list-tests: all
          max-annotations: 10
          fail-on-error: true
          fail-on-empty: true
          only-summary: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
  
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
  
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"

      - name: Clean Workspace
        run: |
          # Remove any temporary files or directories
          rm -rf /home/runner/work/wadiag/wadiag/backend/src/main/resources/private/
        
          # Optionally, remove the entire workspace
          # rm -rf $GITHUB_WORKSPACE
      
        # Use the shell where you created the temporary files
        shell: bash

