name: Java CI with Maven

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: diag
          POSTGRES_USER: diag
          POSTGRES_DB: diag
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Test
        run: mvn --batch-mode test
      
      - name: Test Reporter
        uses: dorny/test-reporter@v1.7.0
        with:
          name: test-results
          path: target/surefire-reports/*.xml
          path-replace-backslashes: false
          reporter: java-junit
          list-suites: all
          list-tests: all
          max-annotations: 10
          fail-on-error: true
          fail-on-empty: true
          only-summary: false
          token: ${{ secrets.GITHUB_TOKEN }}
