name: Java CI with Maven and Tests

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]
  schedule:
    - cron: "0 7 * * *"
    # Schedule: Run every day at 7:00 AM

jobs:
  build:
    runs-on: ubuntu-latest
    environment: env1
    env:
      WORDSAPI_KEY: ${{ secrets.WORDSAPI_KEY }}
      WORDSAPI_URL: ${{ secrets.WORDSAPI_URL }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: diag
          POSTGRES_USER: diag
          POSTGRES_DB: diag
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      fail-fast: false
      matrix:
        language: ["java-kotlin"]

    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Debug Environment Variables
        run: |
          echo "WORDSAPI_KEY: $WORDSAPI_KEY"
          echo "WORDSAPI_URL: $WORDSAPI_URL"

      - name: Build and Test with Maven
        run: cd backend && mvn -B verify --file pom.xml -Dspring.profiles.active=staging

      - name: Test Reporter
        uses: dorny/test-reporter@v1.7.0
        with:
          name: test-results
          path: backend/target/surefire-reports/*.xml
          path-replace-backslashes: false
          reporter: java-junit
          list-suites: all
          list-tests: all
          max-annotations: 10
          fail-on-error: true
          fail-on-empty: true
          only-summary: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
