name: Java CI with Maven and Tests

on:
  push:
    branches: ["master", "develop"]
  pull_request_target:
    branches: ["master", "develop"]
  schedule:
    - cron: "0 7 * * *"
    # Schedule: Run every day at 7:00 AM

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    env:
      WORDSAPI_KEY: ${{ secrets.WORDSAPI_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: diag
          POSTGRES_USER: diag
          POSTGRES_DB: diag
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      fail-fast: false
      matrix:
        language: ["java-kotlin"]

    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug Environment Variables
        run: |
          echo "WORDSAPI_KEY: $WORDSAPI_KEY"
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"

      - name: Build and Test with Maven
        run: cd diag-app && mvn verify --file pom.xml -Dspring.profiles.active=staging

      - name: Test Reporter
        uses: dorny/test-reporter@v1.7.0
        with:
          name: test-results
          path: diag-app/target/surefire-reports/*.xml
          path-replace-backslashes: false
          reporter: java-junit
          list-suites: all
          list-tests: all
          max-annotations: 10
          fail-on-error: true
          fail-on-empty: true
          only-summary: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    environment: staging

    env:
      PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
      PI_USERNAME: ${{ secrets.PI_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set SSH key permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Debug Environment Variables
        run: |
          echo "PUBLIC_IP: $PUBLIC_IP"
          echo "PI_USERNAME: $PI_USERNAME"

      - name: SSH to Raspberry Pi and pull changes
        id: ssh_pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PUBLIC_IP }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd dev/projects/wadiag
            git reset --hard origin/master
            git pull origin master
        continue-on-error: true

      - name: Check if git pull was successful
        if: steps.ssh_pull.outcome == 'failure'
        run: exit 1 # Fail the workflow if git pull failed

      - name: SSH to Raspberry Pi and restart Docker Compose
        id: ssh_compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PUBLIC_IP }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd dev/projects/wadiag
            docker-compose down
            docker-compose --env-file=.env.prod up --build -d
        continue-on-error: true

      - name: Check if Docker Compose restart was successful
        if: steps.ssh_compose.outcome == 'failure'
        run: exit 1 # Fail the workflow if Docker Compose restart failed
